### PR TITLE
Sorts the html index by name.

### PR DESCRIPTION
**Pull request by zenspider**
My tests don't run clean (or I can't tell clean from dirty) so this is
essentially untested.

### CODE REVIEW

**Comment by florence** [comment]
@rpless it is possible to get travis to post about build states on PR's, like coveralls does?

**Comment by samth** [comment]
Travis updates the status you get on the GitHub pull request page.

**Comment by florence** [comment]
I realized that seconds after I commented

**Comment by zenspider** [comment]
[oops, put this on the #31 instead of here]

I'm not married to this PR so feel free to close it as-is. I'm running it locally which has solved my immediate problems so I'm good.

**Comment by florence** [comment]
I'll close this when #31 is closed

**Comment by florence** [comment]
This has been superseded by #37

**Pull request closed without merging**
