### PR TITLE
Fixes GH issue #118 "Division by zero when there are no relevant expressions

### PR DESCRIPTION
**Pull request by jsmaniac**
Fixed by showing 100% coverage in that case (100% is what coveralls.io shows when there are no relevant lines).

### CODE REVIEW

**Comment by jsmaniac** [comment]
I don't think the error with the HEAD version of racket is due to this PR, since it also occurs on the latest, unmodified `master` commit: https://travis-ci.org/jsmaniac/cover/builds/118027669

**Comment by florence** [comment]
Yes, that error is caused by a bug in the codecov API (exposed by some change to the contract system), which I've fixed: https://github.com/codecov/codecov-racket/commit/e20070da30562985bc7affdab8e8f7d7723417b9

How difficult would it be to add a few tests for this?

**Comment by jsmaniac** [comment]
@florence I added some tests for all three changes.

Also, there was a missing close paren on line 194 https://github.com/florence/cover/blob/master/cover/private/html/html.rkt#L194, which seemed to be closed later than it should, I fixed that too.

**Comment by florence** [comment]
Thanks!

**Pull request merged**
